# Test Configuration: RetinaNet with EfficientNet-B0
# Small test run: 100 images, 2 epochs, 128x128, batch size 8

model:
  type: retinanet
  backbone: efficientnet_b0  # Lighter backbone for quick testing
  num_classes: 2  # background + ulcer
  pretrained: true

  # Anchor configuration
  anchor_sizes: [16, 32, 64, 128]  # Adjusted for 128x128 images
  aspect_ratios: [0.5, 1.0, 2.0]

  # Focal loss parameters
  focal_loss_alpha: 0.25
  focal_loss_gamma: 2.0

  # Score thresholds
  score_thresh: 0.05
  nms_thresh: 0.5

training:
  img_size: 128  # Small for quick testing
  batch_size: 8
  num_epochs: 2  # Quick test
  learning_rate: 0.001
  weight_decay: 0.0001

  # Optimizer
  optimizer: AdamW

  # Learning rate scheduler
  scheduler: ReduceLROnPlateau
  scheduler_params:
    mode: min
    factor: 0.5
    patience: 2
    min_lr: 0.00001

  # Composite score weights (recall-focused for medical use)
  composite_weights:
    f1: 0.15
    iou: 0.20
    recall: 0.50  # High priority for not missing ulcers
    precision: 0.15

  # Early stopping (disabled for short test)
  early_stopping_patience: 100

  # Mixed precision training
  use_amp: true

  # Gradient clipping
  max_grad_norm: 1.0

  # Data loading
  num_workers: 0
  pin_memory: true

evaluation:
  confidence_threshold: 0.5
  iou_threshold: 0.5

data:
  train_lmdb: ../../data/test_train.lmdb
  val_lmdb: ../../data/test_val.lmdb
  balanced_sampling: true
  balanced_ratio: 0.5

checkpoint:
  save_dir: ../../checkpoints_test/retinanet
  save_every_n_epochs: 1
  keep_best_only: false
